kind: pipeline
type: docker
name: test

volumes:
  - name: pypirc
    host:
      path: /home/albertyw/.ssh/other/pypirc

steps:
  - name: Test Python
    image: python:3.10
    commands:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > "${HOME}/bin/cc-test-reporter"
      - chmod +x "${HOME}/bin/cc-test-reporter"
      - python setup.py develop
      - pip install -r requirements-test.txt
      - flake8
      - black --line-length 79 --check .
      - mypy . --strict --ignore-missing-imports
      - cc-test-reporter before-build
      - coverage run -m unittest
      - exitcode="$?"
      - coverage xml
      - cc-test-reporter after-build --exit-code "$exitcode"
      - coverage report -m
    environment:
      CC_TEST_REPORTER_ID: 20588a9f3d871445aaee95c9e3f5799cb13812b98b321a34ecebf503578fa2c8

  - name: Upload Python
    image: python:3.10
    commands:
      - pip install twine
      - python setup.py sdist bdist_wheel
      - twine upload dist/*
    volumes:
      - name: pypirc
        path: /root/.pypirc
    when:
      event:
        - tag
