version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  build-and-test:
    resource_class: small
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements-test.txt
          pkg-manager: pip
      - run:
          command: flake8
          name: Lint
      - run:
          command: mypy . --strict --ignore-missing-imports
          name: Type Checking
      - run:
          command: coverage run -m unittest
          name: Test
      - run:
          command: coverage report -m
          name: Test Coverage

workflows:
  main:
    jobs:
      - build-and-test
